

# This file was *autogenerated* from the file solution.sage
from sage.all_cmdline import *   # import sage library

_sage_const_31850 = Integer(31850); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_32 = Integer(32); _sage_const_20 = Integer(20); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_29 = Integer(29)
import pwn
from Crypto.Util.number import getPrime,inverse,bytes_to_long,long_to_bytes
from base64 import b64decode, b64encode
from hashlib import sha256
from os import urandom
import random
import numpy as np
import math
HOST = "103.245.250.31"
PORT = _sage_const_31850 

found = False
while not found:
    s = pwn.remote(HOST,PORT)
    s.recvuntil(": ".encode('utf-8'))
    s.sendline('0'.encode('utf-8'))
    g= s.recvline()[_sage_const_4 :-_sage_const_1 ]
    g = int(g.decode())
    p= s.recvline()[_sage_const_4 :-_sage_const_1 ]
    p = int(p.decode())
    ################
    s.recvuntil(": ".encode('utf-8'))
    s.sendline('1'.encode('utf-8'))
    s.recvuntil(": ".encode('utf-8'))
    m1 = b'\01'*_sage_const_32 
    m1 = b64encode(m1)
    s.sendline(m1)
    text = s.recvline()[_sage_const_20 :-_sage_const_2 ]
    text = text.decode()
    h1 = bytes_to_long(sha256(m1).digest())
    r1,s1 = text.replace(',','').split(" ")
    r1,s1 = int(r1),int(s1)
    print(r1 , s1)
    print(h1)
    #############
    s.recvuntil(": ".encode('utf-8'))
    s.sendline('1'.encode('utf-8'))
    s.recvuntil(": ".encode('utf-8'))
    m2 = b'\03'*_sage_const_32 
    m2 = b64encode(m2)
    s.sendline(m2)
    text1 = s.recvline()[_sage_const_20 :-_sage_const_2 ]
    text1 = text1.decode()
    h2 = bytes_to_long(sha256(m2).digest())
    r2,s2 = text1.replace(',','').split(" ")
    r2,s2 = int(r2),int(s2)
    print(r2 , s2)
    print(h2)
    #######
    Z = Zmod(p-_sage_const_1 )
    A = matrix(Z, _sage_const_2 , [[s1, r1],[_sage_const_3 *s2,r2]]) 
    y = vector(Z, _sage_const_2 , [h1,h2])
    k,x = A.solve_right(y)
    k = ZZ(k)
    if k % _sage_const_2  ==_sage_const_0 :
        print("fail")
    x = ZZ(x)
    print(pow(g,h1,p)==(pow(pow(g,x,p),r1,p)*pow(r1,s1,p))%p)
    #######
    s.recvuntil(": ".encode('utf-8'))
    s.sendline('3'.encode('utf-8'))
    m3 = s.recvline()[_sage_const_29 :-_sage_const_1 ]
    ######
   
    
    h3 = bytes_to_long(sha256(m3).digest())
    r2 = g
    s3 = (h3 - x*r2) % (p-_sage_const_1 )
    print(b64encode(long_to_bytes(r1)))
    print(b64encode(long_to_bytes(s3)))
    
    s.recvuntil(": ".encode('utf-8'))
    s.sendline(b64encode(long_to_bytes(r2)))
    s.recvuntil(": ".encode('utf-8'))
    s.sendline(b64encode(long_to_bytes(s3)))   
    ans = s.recvline()
    print(ans)
    if "Congratulation" in ans.decode():
        print(ans)
        break
        s.close()
    else:
        s.close()

